name: pailmail
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0

  flutter_expanded_tile: ^0.3.7
  date_picker_plus: ^1.1.3
  image_picker: ^1.0.4
  awesome_dialog:
  country_picker: ^2.0.27

  animated_toggle_switch: ^0.8.0
  animated_text_kit: ^4.2.2
  flutter_advanced_drawer: ^1.3.5
  easy_localization: ^3.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.1
  email_validator: ^2.1.17
  provider: ^6.0.5

  image_fade: ^0.6.2
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  skeletonizer: ^0.8.0

  popup_banner: ^1.0.0


#  share_files_and_screenshot_widgets: ^1.0.5

#  share_plus: ^6.0.1

flutter_native_splash:
  color: "#003AFC"
  image: assets/images/logo.png
  android: true
  ios: true

  android_12:
    image: assets/logo.png



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
